name: lender-vaultv3

plugins:
  - name: solidity
  - name: vyper
  - name: etherscan
  - name: hardhat
  - name: infura

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.7.3

  - name: yearn-vaults-v3
    github: jmonteer/yearn-vaults-v3
    branch: master

  - name: strategy-comp-v3 
    github: jmonteer/yearnv3-strat-compoundv3-lender
    branch: master

  - name: strategy-aave-v2 
    github: bufander/yearnv3-ape-aave-lender
    branch: master

  - name: strategy-comp-v2 
    github: spalen0/yearnv3-strat-compv2-lender
    branch: master

  - name: debt-manager
    github: jmonteer/yearnv3-lending-vault-periphery
    branch: master

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura
